### ISSUE TITLE
theme pcmanfm like thunar

### ISSUE THREAD

**Issue by siduck** [Everblush/gtk#1]
would it be possible to add css for pcmanfm and make it look better like thunar too?

![image](https://user-images.githubusercontent.com/59060246/155933197-9276539b-a3c0-41f0-91c8-e3c00a53043a.png)

thunar on left

**Comment by mngshm** [comment]
Ok would try today :)) + a full fledged gui theme is WIP, so after its ready there won't be much hassle

**Comment by siduck** [comment]
> Ok would try today :)) + a full fledged gui theme is WIP, so after its ready there won't be much hassle

keep this issue opened until its fixed
