### ISSUE TITLE
remove my access permission

### ISSUE THREAD

**Issue by siduck** [Everblush/gtk#3]
Im still able to clone the repo via ssh, Since you've allied with the coomers, remove me as a collaborator here. 

![image](https://user-images.githubusercontent.com/59060246/159837514-0338cbdb-9473-44ee-9ca0-062c20096b46.png)

**Comment by Mangeshrex** [comment]
I wonder how childish you are my friend(ex). Like i  wanna laugh at this. What has that telegram group thing have to do with this organisation / repository ? I removed you from org cuz you were not gna contribute to me anymore. But you contributed to this repo. so how will I remove you from contributers list? + dont i have any other stuff to do in my daily routine ? **Please** dont be silly and drag things to different places.

**Comment by siduck** [comment]
Im not telling myself to remove from the contributers list lol do you even read what i said? I literally have write permissions to this repo. Im just telling that to remove it. What will a non org member do with write permissions in an org repo? Think before you talk

**Comment by siduck** [comment]
yea make fun of me in your group, Look how nsfw offtopic they converse in your group lool 

![image](https://user-images.githubusercontent.com/59060246/160223761-fd60d1d0-f883-4cae-b4e8-b19d91df6037.png)

the irony XD

**Comment by alok8bb** [comment]
@siduck Are you this dumb to take some random telegram group's fight to GitHub projects?

**Comment by siduck** [comment]
> @siduck Are you this dumb to take some random telegram group's fight to GitHub projects?

He's free to delete this issue, I dont want to join that group or pm him. if you're starting this again here then you're the dumb one. Everything's cool and calm now

**Comment by alok8bb** [comment]
What would you create in the first place xD

**Comment by siduck** [comment]
you mean to say "why"?

**Comment by alok8bb** [comment]
Yes

**Comment by siduck** [comment]
read my comment again. I didnt wanted to pm him nor wanted to join your group and as this ssh issue was related to the repo so I told it here itself.

**Comment by alok8bb** [comment]
That's fine but what was the need for the line "Since you've allied with the coomers"?

**Comment by siduck** [comment]
thats was the reason for me not having the ssh access in the first place

**Comment by alok8bb** [comment]
> @siduck Are you this dumb to take some random telegram group's fight to GitHub projects?

.

**Comment by siduck** [comment]
> read my comment again. I didnt wanted to pm him nor wanted to join your group and as this ssh issue was related to the repo so I told it here itself.

.

**Comment by alok8bb** [comment]
> That's fine but what was the need for the line "Since you've allied with the coomers"?

.

**Comment by siduck** [comment]
> thats was the reason for me not having the ssh access in the first place so i just told it, rather than having mangrex to think why i am giving back the ssh rights

.

**Comment by alok8bb** [comment]
> @siduck Are you this dumb to take some random telegram group's fight to GitHub projects?

.

**Comment by siduck** [comment]
> > @siduck Are you this dumb to take some random telegram group's fight to GitHub projects?
> 
> He's free to delete this issue, I dont want to join that group or pm him. if you're starting this again here then you're the dumb one. Everything's cool and calm now. I did tell him to delete the issue ages ago or i'll just delete my comments if he's unable to delete the issue

.

**Comment by siduck** [comment]
@Mangeshrex delete this issue, the message is conveyed, what are you even waiting for?
