### ISSUE TITLE
Selected texts are not visible

### ISSUE THREAD

**Issue by freakingeek** [Everblush/gtk#4]
@Mangeshrex 

Hi!
I think the selected texts are not visible enough in terminal or in chrome url bar ...

**Comment by freakingeek** [comment]
@samuelnihbos

**Comment by samuelnihbos** [comment]
Hi @sttatusx! Thank you for the report, we will take a deeper look and fix this ASAP

**Comment by freakingeek** [comment]
Hi again! ( @samuelnihbos )

![image](https://user-images.githubusercontent.com/59373143/172467322-aa592b73-230c-4d54-bc9f-aef2484dec20.png)

This is brave and I select half the text and it is not visible!

**Comment by samuelnihbos** [comment]
ive had same problem like yours, will push the fix asap

**Comment by freakingeek** [comment]
> ive had same problem like yours, will push the fix asap

Thanks :heart:

**Comment by samuelnihbos** [comment]
as per [https://github.com/Everblush/gtk/commit/40dd115700143b11f2296999ac48499d16c5a1aa](this) commit, the problem will be fixed. Feel free to reopen this issue or make a new issue if the problem persist

**Comment by mngshm** [comment]
good work @samuelnihbos
