### ISSUE TITLE
Update Makefile

### ISSUE THREAD

**Issue by paulhersch** [Everblush/gtk#5]
the current makefile doesn't work, as there is no src folder anymore

**Comment by mngshm** [comment]
Uhh ok I'll push the fix in an hour but till then you can just make a directory 
`mkdir src`
If you see another error as no gtk.scss found then touch that file in respective dir. 

These errors cause no issues on the theme

**Comment by samuelnihbos** [comment]
can you specify which part is "doesn't work"? I just cloned and try to install the theme with no problem

**Comment by samuelnihbos** [comment]
@paulhersch can you please specify on which part the makefile doesn't work, i've tested it yesterday and i'm not facing any errors

**Comment by paulhersch** [comment]
the `all` part in the Makefile does error out, no?

**Comment by samuelnihbos** [comment]
no, it throws no errors, have you trued to run make install and see what happened?

**Comment by paulhersch** [comment]
well it doesn't work for me because i use NixOS so there is no /usr directory...
after writing my own derivation the builder originally failed because of the 
```
all:
	mkdir -p gtk-3.0
	sass src/gtk-3.0/gtk.scss gtk-3.0/gtk.css
```
part in the Makefile. My current build instruction looks like this
```
        preBuild = ''
		mkdir -p $out/share/themes/Everblush-gtk/gtk-3.0
	'';
	buildPhase = ''
		runHook preBuild
                sass $src/sass/gtk-3.0/gtk.scss $out/share/themes/Everblush-gtk/gtk-3.0/gtk.css
	'';
	installPhase = ''
		cp -n -r $src/* $out/share/themes/Everblush-gtk/
	'';
```
which works. Thats why i opened this issue, the command `sass src/gtk-3.0/gtk.scss gtk-3.0/gtk.css` in the original makefile just didnt work

**Comment by mngshm** [comment]
ohh have you got that working ? if so i would be happy if you make a pr which has a fix for NixOS Users.

**Comment by paulhersch** [comment]
i mean i just wrote a small derivation so that i could have it hardcoded in my config (so its basically "packaged" if you can say that).

btw
i think i found some weirdness (idk if this is intended or not) but using the thing above actually creates another theme that is not everblush, pcmanfm for scale:

with sass build command thingy:
![07-04-210939](https://user-images.githubusercontent.com/74120050/177207708-aa8aed49-8723-49f9-b953-168dfd46b42c.png)

without sass build command:
![07-04-211128](https://user-images.githubusercontent.com/74120050/177207747-6919601c-669e-442e-8539-9cae972acf56.png)

i think you are overwriting the transscripted css with the current Makefile (which doesn't make sense, but creates the correct theme), but i have never touched a Makefile so I am not entirely sure.

**Comment by paulhersch** [comment]
closing this as it doesn't seem to affect normal installations
